// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhOM7roNX3_Xh6jMe9SNovhi0PJqoadzU',
    appId: '1:549057023378:web:70064fb8736bd27d20c54b',
    messagingSenderId: '549057023378',
    projectId: 'timescraper-edd98',
    authDomain: 'timescraper-edd98.firebaseapp.com',
    storageBucket: 'timescraper-edd98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCeIqoKBGdgxQ9tl-JYWa8dv4I_mJBmg',
    appId: '1:549057023378:android:5fdce1b32a4a0bfb20c54b',
    messagingSenderId: '549057023378',
    projectId: 'timescraper-edd98',
    storageBucket: 'timescraper-edd98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBftJTvBS7jia742Jqsshdhoz4sYqlEpXU',
    appId: '1:549057023378:ios:d469b7111d0faf9f20c54b',
    messagingSenderId: '549057023378',
    projectId: 'timescraper-edd98',
    storageBucket: 'timescraper-edd98.firebasestorage.app',
    iosBundleId: 'com.example.timescraper.timescraper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBftJTvBS7jia742Jqsshdhoz4sYqlEpXU',
    appId: '1:549057023378:ios:d469b7111d0faf9f20c54b',
    messagingSenderId: '549057023378',
    projectId: 'timescraper-edd98',
    storageBucket: 'timescraper-edd98.firebasestorage.app',
    iosBundleId: 'com.example.timescraper.timescraper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhOM7roNX3_Xh6jMe9SNovhi0PJqoadzU',
    appId: '1:549057023378:web:4add32c86955648a20c54b',
    messagingSenderId: '549057023378',
    projectId: 'timescraper-edd98',
    authDomain: 'timescraper-edd98.firebaseapp.com',
    storageBucket: 'timescraper-edd98.firebasestorage.app',
  );
}
